# Generated by Django 4.2.6 on 2023-11-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comercio', '0002_proveedor_alter_cliente_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=15)),
                ('decripcion', models.TextField(max_length=50)),
                ('precio', models.FloatField()),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('codigo_articulo', models.CharField(max_length=15)),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
    ]
